food_blogs/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    
    # Add category field
    category = SelectField('Category', choices=[
        ('appetizer', 'Appetizer'),
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('dinner', 'Dinner'),
        ('drinks', 'Drinks')
    ], validators=[DataRequired()])

    submit = SubmitField('Create Post')

food_blogs/blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from food_blogs import db
from food_blogs.models import BlogPost
from food_blogs.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()
    print(form)
    if form.validate_on_submit():
        
        post = BlogPost(title=form.title.data, text=form.text.data, category=form.category.data,user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Post Created', 'success')
        return redirect(url_for('core.info', category_name=form.category.data))  # Redirect to the category page
    return render_template('create_post.html', form=form)


# int: makes sure that the blog_post_id gets passed as in integer
# instead of a string so we can look it up later.
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    # grab the requested blog post by id number or return 404
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )

@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

food_blogs/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from food_blogs import db
from werkzeug.security import generate_password_hash,check_password_hash
from food_blogs.models import User, BlogPost
from food_blogs.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from food_blogs.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

        if user.check_password(form.password.data) and user is not None:
            #Log in the user

            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

food_blogs/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>

</div>

{% endblock content %}

food_blogs/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <ul class="nav">

  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('core.info') }}">About Us</a>
  </li>
    {% if current_user.is_authenticated %}
    <li class="nav-link"><a href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li class="nav-link"><a href="{{ url_for('users.account') }}">Account</a></li>
    <li class="nav-link"><a href="{{ url_for('blog_posts.create_post') }}">Create Post</a></li>
    {% else %}
    <li class="nav-link"><a href="{{ url_for('users.login') }}">Log In</a></li>
    <li class="nav-link"><a href="{{ url_for('users.register') }}">Register</a></li>
    {% endif %}

</ul>
<div class="container">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

food_blogs/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

food_blogs/templates/category.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>{{ category_name.title() }} Recipes</h1>
    <p>Explore delicious {{ category_name }} recipes created by our community!</p>
  </div>

  <div class="container">
    {% for post in blog_posts.items %}
    <div class="card mb-4">
      <div class="card-body">
        <h2><a class="card-title" href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
      </div>
    </div>
    {% endfor %}

    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.category', category_name=category_name, page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
          <li class="page-item">
            <a class="page-link" href="{{ url_for('core.category', category_name=category_name, page=page_num) }}">{{ page_num }}</a>
          </li>
          {% endif %}
        {% endfor %}
      </ul>
    </nav>
  </div>
{% endblock %}

food_blogs/templates/create_post.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <h1>Create a New Post</h1>
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.title.label(class="form-control-label") }}
        {{ form.title(class="form-control form-control-lg") }}
      </div>
      <div class="form-group">
        {{ form.text.label(class="form-control-label") }}
        {{ form.text(class="form-control form-control-lg") }}
      </div>
      <div class="form-group">
        {{ form.category.label(class="form-control-label") }}
        {{ form.category(class="form-control form-control-lg") }}
      </div>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary btn-block") }}
      </div>
    </form>
  </div>
{% endblock %}

food_blogs/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron" style="background-color: #f8f9fa; padding: 30px; border-radius: 8px; text-align: center; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
  <h1 style="font-size: 3rem; margin-bottom: 10px; color: #343a40;">VibrantVeggies</h1>
  <p style="font-size: 1.25rem; color: #6c757d;">Welcome to Food Blog!</p>
</div>


  <div class="container">
    <div class="categories" style="display: flex; flex-wrap: wrap; justify-content: center; gap: 20px;">
        <div style="text-align: center;">
            <a href="{{ url_for('core.info', category_name='appetizers') }}">
                <img src="{{ url_for('static', filename='images/appetizer.png') }}" alt="Appetizers" 
                     style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover; border: 2px solid #ddd;">
            </a>
            <p style="margin-top: 10px;">Appetizers</p>
        </div>
        <div style="text-align: center;">
            <a href="{{ url_for('core.info', category_name='breakfast') }}">
                <img src="{{ url_for('static', filename='images/breakfast.png') }}" alt="Breakfast" 
                     style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover; border: 2px solid #ddd;">
            </a>
            <p style="margin-top: 10px;">Breakfast</p>
        </div>
        <div style="text-align: center;">
            <a href="{{ url_for('core.info', category_name='lunch') }}">
                <img src="{{ url_for('static', filename='images/lunch.png') }}" alt="Lunch" 
                     style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover; border: 2px solid #ddd;">
            </a>
            <p style="margin-top: 10px;">Lunch</p>
        </div>
        <div style="text-align: center;">
            <a href="{{ url_for('core.info', category_name='dinner') }}">
                <img src="{{ url_for('static', filename='images/dinner.png') }}" alt="Dinner" 
                     style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover; border: 2px solid #ddd;">
            </a>
            <p style="margin-top: 10px;">Dinner</p>
        </div>
        <div style="text-align: center;">
            <a href="{{ url_for('core.info', category_name='drinks') }}">
                <img src="{{ url_for('static', filename='images/drinks.png') }}" alt="Drinks" 
                     style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover; border: 2px solid #ddd;">
            </a>
            <p style="margin-top: 10px;">Drinks</p>
        </div>
    </div>
  </div>

  <div class="container">
    {# Go through each blog post #}
    {% for post in blog_posts.items %}
      <div class="card" >
        <div class="card-body">
          <h2><a class="card-title" href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          <p><span style="font-weight: bold;">Category:</span> {{ post.category }}</p>
          <p><span style="font-weight: bold; color: black;">Written By:</span> {{ post.author.username }}</p>
          <p><span style="font-weight: bold;">Published on:</span> {{ post.date.strftime('%Y-%m-%d') }}</p>
          <p class="card-text">{{ post.text[:100] }}...</p>
          <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
        </div>
      </div>
    {% endfor %}
    
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
            <li class="page-item disabled">
              <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    </nav>
  </div>
{% endblock %}

food_blogs/templates/info.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>VibrantVeggies</h1>
  <p>Welcome to VibrantVeggies—your go-to destination for fresh, flavorful, and creative recipes! Whether you're looking for a quick breakfast, a hearty lunch, a delicious dinner, or a refreshing drink, we've got you covered. Our blog is a community-driven space where food enthusiasts can explore and share their culinary creations. With easy-to-navigate categories and visually appealing posts, VibrantVeggies makes discovering new recipes a breeze. Join us in celebrating the art of cooking and bring vibrant flavors to your kitchen!</p>
  <img src="{{ url_for('static', filename='images/p1.png') }}" alt="Description of Image" style="width: 100%; height: auto;">
</div>

{% endblock %}

food_blogs/templates/login.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}
    {{ form.password.label }} {{ form.password() }}
    {{ form.submit() }}
</form>
{% endblock %}

food_blogs/templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}<br>
    {{ form.username.label }} {{ form.username() }}<br>
    {{ form.password.label }} {{ form.password() }}<br>
    {{ form.pass_confirm.label }} {{ form.pass_confirm() }}<br>
    {{ form.submit() }}
</form>
{% endblock %}

food_blogs/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for post in blog_posts.items %}

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}
     